# Generated by Django 5.2.4 on 2025-11-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='refasset',
            name='CreatedBy',
            field=models.ForeignKey(db_column='CreatedBy', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refasset',
            name='ModifiedBy',
            field=models.ForeignKey(db_column='ModifiedBy', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modified_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
