# Generated by Django 5.2.4 on 2025-10-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ast_document',
            name='TemplateId',
            field=models.ForeignKey(blank=True, db_column='TemplateId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ast_documents', to='core.ref_template'),
        ),
    ]
