# Generated by Django 4.2.23 on 2025-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_refasset_createdby_alter_refasset_modifiedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Product_Group',
            fields=[
                ('ProductGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductGroupName', models.CharField(max_length=250)),
                ('ProductGroupCode', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'db_table': 'ins_ref_product_group',
            },
        ),
    ]
