# Generated by Django 5.2.4 on 2025-11-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ast_document_templateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref_template',
            name='CashFlowId',
        ),
        migrations.AlterField(
            model_name='ref_template',
            name='AccountId',
            field=models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='core.ref_account'),
        ),
        migrations.AlterField(
            model_name='ref_template',
            name='IsVat',
            field=models.BooleanField(db_column='IsVat', default=False),
        ),
        migrations.AlterField(
            model_name='ref_template',
            name='TemplateName',
            field=models.CharField(max_length=70),
        ),
    ]
