# Generated by Django 4.2.23 on 2025-12-25 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_ref_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Product_Type',
            fields=[
                ('ProductTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTypeName', models.CharField(max_length=250)),
                ('ProductTypeCode', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_product_types', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_product_types', to=settings.AUTH_USER_MODEL)),
                ('ProductGroupId', models.ForeignKey(db_column='ProductGroupId', on_delete=django.db.models.deletion.PROTECT, related_name='product_types', to='core.ref_product_group')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
                'db_table': 'ins_ref_product_type',
            },
        ),
    ]
