# Generated by Django 5.2.4 on 2025-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ref_template_cashflowid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='St_Balance',
            fields=[
                ('StbalanceId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('StbalanceCode', models.CharField(max_length=30)),
                ('StbalanceName', models.CharField(max_length=150)),
                ('BeginBalance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('EndBalance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('Order', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Stock Balance',
                'verbose_name_plural': 'Stock Balances',
                'db_table': 'st_balance',
                'ordering': ['Order', 'StbalanceCode'],
            },
        ),
    ]
