# Generated by Django 4.2.23 on 2025-12-25 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_ref_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=150)),
                ('ProductCode', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_products', to=settings.AUTH_USER_MODEL)),
                ('ProductTypeId', models.ForeignKey(db_column='ProductTypeId', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.ref_product_type')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'ins_ref_product',
            },
        ),
    ]
