# Generated by Django 5.2.4 on 2025-11-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_st_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref_account_type',
            name='CT1',
        ),
        migrations.RemoveField(
            model_name='ref_account_type',
            name='CT2',
        ),
        migrations.AddField(
            model_name='ref_account_type',
            name='StBalanceId',
            field=models.ForeignKey(blank=True, db_column='StBalanceId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='core.st_balance'),
        ),
    ]
