# Generated by Django 4.2.23 on 2025-12-25 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_ref_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Item_Type',
            fields=[
                ('ItemTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemTypeName', models.CharField(max_length=250)),
                ('ItemTypeCode', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_item_types', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_item_types', to=settings.AUTH_USER_MODEL)),
                ('ParentId', models.ForeignKey(blank=True, db_column='ParentId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_item_types', to='core.ref_item_type')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'db_table': 'ins_ref_item_type',
            },
        ),
    ]
