# Generated by Django 5.2.4 on 2025-11-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ref_account_type_ct1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='St_Income',
            fields=[
                ('StIncomeId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('StIncome', models.CharField(max_length=30)),
                ('StIncomeName', models.CharField(max_length=150)),
                ('EndBalance', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('Order', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Stock Income',
                'verbose_name_plural': 'Stock Incomes',
                'db_table': 'st_income',
                'ordering': ['Order', 'StIncome'],
            },
        ),
    ]
