# Generated by Django 5.2.4 on 2025-11-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_st_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_account_type',
            name='StIncomeId',
            field=models.ForeignKey(blank=True, db_column='StIncomeId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='core.st_income'),
        ),
    ]
