# Generated by Django 5.2.4 on 2025-11-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ref_account_type_stincomeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='St_CashFlow',
            fields=[
                ('StCashFlowId', models.SmallIntegerField(db_column='StCashFlowId', primary_key=True, serialize=False)),
                ('StCashFlowCode', models.CharField(db_column='StCashFlowCode', max_length=30)),
                ('StCashFlowName', models.CharField(db_column='StCashFlowName', max_length=150)),
                ('EndBalance', models.DecimalField(db_column='EndBalance', decimal_places=6, default=0, max_digits=24)),
                ('Order', models.SmallIntegerField(db_column='Order')),
                ('IsVisible', models.BooleanField(db_column='IsVisible', default=True)),
            ],
            options={
                'verbose_name': 'Cash Flow Category',
                'verbose_name_plural': 'Cash Flow Categories',
                'db_table': 'st_cashflow',
                'ordering': ['Order', 'StCashFlowCode'],
            },
        ),
    ]
