# Generated by Django 4.2.23 on 2025-12-25 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_ref_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Item_Question',
            fields=[
                ('ItemQuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemQuestionName', models.CharField(max_length=200)),
                ('ItemQuestionCode', models.CharField(max_length=50)),
                ('QuestionType', models.CharField(max_length=100)),
                ('FieldType', models.CharField(max_length=100)),
                ('FieldValue', models.CharField(blank=True, max_length=100, null=True)),
                ('Order', models.IntegerField(db_column='Order')),
                ('FieldMask', models.CharField(blank=True, max_length=500, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_item_questions', to=settings.AUTH_USER_MODEL)),
                ('ItemId', models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.PROTECT, related_name='item_questions', to='core.ref_item')),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_item_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Question',
                'verbose_name_plural': 'Item Questions',
                'db_table': 'ins_ref_item_question',
                'ordering': ['Order', 'ItemQuestionCode'],
            },
        ),
    ]
