# Generated by Django 5.2.4 on 2025-11-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_st_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinventory',
            name='IsDelete',
            field=models.BooleanField(default=False),
        ),
    ]
