# Generated by Django 4.2.23 on 2025-12-25 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_ref_item_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Risk_Type',
            fields=[
                ('RiskTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('RiskTypeName', models.CharField(max_length=200)),
                ('RiskTypeCode', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_risk_types', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_risk_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Type',
                'verbose_name_plural': 'Risk Types',
                'db_table': 'ins_ref_risk_type',
            },
        ),
    ]
