# Generated by Django 4.2.23 on 2025-12-25 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_ref_risk_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Risk',
            fields=[
                ('RiskId', models.AutoField(primary_key=True, serialize=False)),
                ('RiskName', models.CharField(max_length=200)),
                ('RiskCode', models.CharField(max_length=50)),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_risks', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_risks', to=settings.AUTH_USER_MODEL)),
                ('ParentId', models.ForeignKey(blank=True, db_column='ParentId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_risks', to='core.ref_risk')),
                ('RiskTypeId', models.ForeignKey(db_column='RiskTypeId', on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='core.ref_risk_type')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
                'db_table': 'ins_ref_risk',
            },
        ),
    ]
