# Generated by Django 4.2.23 on 2025-12-25 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_ref_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Ins_Client',
            fields=[
                ('InsClientId', models.AutoField(primary_key=True, serialize=False)),
                ('InsClientCode', models.CharField(max_length=50)),
                ('OrgName', models.CharField(blank=True, max_length=100, null=True)),
                ('OrgRegister', models.CharField(blank=True, max_length=12, null=True)),
                ('IsOrg', models.BooleanField(default=False)),
                ('DistrictId', models.IntegerField(blank=True, null=True)),
                ('IsPolitics', models.BooleanField(default=False)),
                ('IsInvestor', models.BooleanField(default=False)),
                ('FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('DriverLicenceNo', models.CharField(blank=True, max_length=50, null=True)),
                ('EmergencyContact', models.CharField(blank=True, max_length=150, null=True)),
                ('Gender', models.CharField(blank=True, max_length=50, null=True)),
                ('NationalityId', models.IntegerField(blank=True, null=True)),
                ('PhotoPath', models.CharField(blank=True, max_length=250, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('DriverLicentceYear', models.DateField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('ClientId', models.ForeignKey(db_column='ClientId', on_delete=django.db.models.deletion.PROTECT, related_name='ins_clients', to='core.refclient')),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ins_clients', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_ins_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Client',
                'verbose_name_plural': 'Insurance Clients',
                'db_table': 'ins_ref_client',
            },
        ),
    ]
