# Generated by Django 4.2.23 on 2025-12-25 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_ref_ins_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Policy_Template',
            fields=[
                ('PolicyTemplateId', models.AutoField(primary_key=True, serialize=False)),
                ('PolicyTemplateName', models.CharField(max_length=200)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('FilePath', models.CharField(blank=True, max_length=250, null=True)),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_policy_templates', to=settings.AUTH_USER_MODEL)),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_policy_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Template',
                'verbose_name_plural': 'Policy Templates',
                'db_table': 'ins_ref_policy_template',
            },
        ),
    ]
