# Generated by Django 4.2.23 on 2025-12-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ref_policy_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Policy_Template_Transaction',
            fields=[
                ('PolicyTemplateTransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('IsDebit', models.BooleanField()),
                ('CalculationType', models.BooleanField(default=False)),
                ('AccountId', models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_template_transactions', to='core.ref_account')),
                ('CashFlowId', models.ForeignKey(blank=True, db_column='CashFlowId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_template_transactions', to='core.ref_cashflow')),
                ('PolicyTemplateId', models.ForeignKey(db_column='PolicyTemplateId', on_delete=django.db.models.deletion.PROTECT, related_name='template_transactions', to='core.ref_policy_template')),
            ],
            options={
                'verbose_name': 'Policy Template Transaction',
                'verbose_name_plural': 'Policy Template Transactions',
                'db_table': 'ins_ref_policy_template_transaction',
            },
        ),
    ]
