# Generated by Django 4.2.23 on 2025-12-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ref_policy_template_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Policy_Template_Detail',
            fields=[
                ('PolicyTemplateDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('CommPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ItemId', models.ForeignKey(blank=True, db_column='ItemId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_template_details', to='core.ref_item')),
                ('PolicyTemplateId', models.ForeignKey(db_column='PolicyTemplateId', on_delete=django.db.models.deletion.PROTECT, related_name='template_details', to='core.ref_policy_template')),
                ('ProductId', models.ForeignKey(blank=True, db_column='ProductId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_template_details', to='core.ref_product')),
                ('RiskId', models.ForeignKey(blank=True, db_column='RiskId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy_template_details', to='core.ref_risk')),
            ],
            options={
                'verbose_name': 'Policy Template Detail',
                'verbose_name_plural': 'Policy Template Details',
                'db_table': 'ins_ref_policy_template_detail',
            },
        ),
    ]
