# Generated by Django 4.2.23 on 2025-12-27 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_ref_policy_template_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Channel',
            fields=[
                ('ChannelId', models.AutoField(primary_key=True, serialize=False)),
                ('ChannelName', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'db_table': 'ins_ref_channel',
            },
        ),
        migrations.CreateModel(
            name='Ref_Branch',
            fields=[
                ('BranchId', models.AutoField(primary_key=True, serialize=False)),
                ('BranchCode', models.CharField(max_length=4)),
                ('BranchName', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'ins_ref_branch',
            },
        ),
    ]
