# Generated by Django 4.2.23 on 2025-12-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ref_channel_ref_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_branch',
            name='DirectorName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
