# Generated by Django 4.2.23 on 2025-12-27 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_ref_branch_directorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Main',
            fields=[
                ('PolicyId', models.AutoField(primary_key=True, serialize=False)),
                ('PolicyNo', models.CharField(max_length=25)),
                ('BeginDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('CurrencyExchange', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('DirectorName', models.CharField(blank=True, max_length=15, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsLock', models.BooleanField(default=False)),
                ('IsPosted', models.BooleanField(default=False)),
                ('Description', models.CharField(blank=True, max_length=60, null=True)),
                ('StatusId', models.SmallIntegerField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('AgentBranchId', models.ForeignKey(blank=True, db_column='AgentBranchId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.ref_branch')),
                ('AgentChannelId', models.ForeignKey(blank=True, db_column='AgentChannelId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.ref_channel')),
                ('AgentId', models.ForeignKey(blank=True, db_column='AgentId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_policies', to='core.refclient')),
                ('ApprovedBy', models.ForeignKey(blank=True, db_column='ApprovedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('ClientId', models.ForeignKey(db_column='ClientId', on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.refclient')),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('CurrencyId', models.ForeignKey(blank=True, db_column='CurrencyId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.ref_currency')),
                ('ModifiedBy', models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_policies', to=settings.AUTH_USER_MODEL)),
                ('PolicyTemplateId', models.ForeignKey(blank=True, db_column='PolicyTemplateId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.ref_policy_template')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'ins_policy_main',
            },
        ),
    ]
