# Generated by Django 4.2.23 on 2025-12-27 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_make_fks_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Main_Schedule',
            fields=[
                ('PolicyPaymentScheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('DueDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('PolicyId', models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.PROTECT, related_name='payment_schedules', to='core.policy_main')),
            ],
            options={
                'verbose_name': 'Policy Payment Schedule',
                'verbose_name_plural': 'Policy Payment Schedules',
                'db_table': 'ins_policy_main_schedule',
            },
        ),
        migrations.CreateModel(
            name='Policy_Main_Product_Risk_Item',
            fields=[
                ('PolicyDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('CommissionPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ItemId', models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_details', to='core.ref_item')),
                ('PolicyId', models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_details', to='core.policy_main')),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_details', to='core.ref_product')),
                ('RiskId', models.ForeignKey(db_column='RiskId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_details', to='core.ref_risk')),
            ],
            options={
                'verbose_name': 'Policy Detail',
                'verbose_name_plural': 'Policy Details',
                'db_table': 'ins_policy_main_product_risk_item',
            },
        ),
        migrations.CreateModel(
            name='Policy_Main_Coinsurance',
            fields=[
                ('PolicyCoInsuredId', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('ClientId', models.ForeignKey(db_column='ClientId', on_delete=django.db.models.deletion.PROTECT, related_name='coinsurance_policies', to='core.refclient')),
                ('PolicyId', models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.PROTECT, related_name='coinsurance', to='core.policy_main')),
            ],
            options={
                'verbose_name': 'Policy Coinsurance',
                'verbose_name_plural': 'Policy Coinsurance',
                'db_table': 'ins_policy_main_coinsurance',
            },
        ),
    ]
