# Generated by Django 4.2.23 on 2025-12-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_policy_main_schedule_policy_main_product_risk_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Main_Files',
            fields=[
                ('PolicyAttachmentId', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=50)),
                ('FilePath', models.CharField(max_length=100)),
                ('PolicyId', models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.policy_main')),
            ],
            options={
                'verbose_name': 'Policy File',
                'verbose_name_plural': 'Policy Files',
                'db_table': 'ins_policy_main_files',
            },
        ),
    ]
