# Generated by Django 4.2.23 on 2025-12-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_policy_main_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy_main_files',
            name='PolicyId',
            field=models.ForeignKey(db_column='PolicyId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_files', to='core.policy_main'),
        ),
    ]
