# Generated by Django 4.2.23 on 2025-12-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_policy_main_files_policyid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Template_Product',
            fields=[
                ('TemplateProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.PROTECT, related_name='template_products', to='core.ref_product')),
            ],
            options={
                'verbose_name': 'Template Product',
                'verbose_name_plural': 'Template Products',
                'db_table': 'ins_ref_template_product',
            },
        ),
        migrations.CreateModel(
            name='Ref_Template_Product_Item',
            fields=[
                ('TemplateProductItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemId', models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.PROTECT, related_name='template_product_items', to='core.ref_item')),
                ('TemplateProductId', models.ForeignKey(db_column='TemplateProductId', on_delete=django.db.models.deletion.PROTECT, related_name='template_product_items', to='core.ref_template_product')),
            ],
            options={
                'verbose_name': 'Template Product Item',
                'verbose_name_plural': 'Template Product Items',
                'db_table': 'ins_ref_template_product_item',
            },
        ),
        migrations.CreateModel(
            name='Ref_Template_Product_Item_Risk',
            fields=[
                ('TemplateProductItemRiskId', models.AutoField(primary_key=True, serialize=False)),
                ('CommPercent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('RiskId', models.ForeignKey(db_column='RiskId', on_delete=django.db.models.deletion.PROTECT, related_name='template_product_item_risks', to='core.ref_risk')),
                ('TemplateProductItemId', models.ForeignKey(db_column='TemplateProductItemId', on_delete=django.db.models.deletion.PROTECT, related_name='template_product_item_risks', to='core.ref_template_product_item')),
            ],
            options={
                'verbose_name': 'Template Product Item Risk',
                'verbose_name_plural': 'Template Product Item Risks',
                'db_table': 'ins_ref_template_product_item_risk',
            },
        ),
        migrations.AlterModelTable(
            name='ref_policy_template',
            table='ins_ref_template',
        ),
        migrations.DeleteModel(
            name='Ref_Policy_Template_Detail',
        ),
        migrations.AddField(
            model_name='ref_template_product',
            name='TemplateId',
            field=models.ForeignKey(db_column='TemplateId', on_delete=django.db.models.deletion.PROTECT, related_name='template_products', to='core.ref_policy_template'),
        ),
    ]
