# Generated by Django 4.2.23 on 2025-12-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ref_template_product_ref_template_product_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy_Main_Product_Risk_Item',
        ),
    ]
