# Generated by Django 4.2.23 on 2025-12-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_policy_main_product_risk_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Main_Product',
            fields=[
                ('PolicyMainProductId', models.AutoField(primary_key=True, serialize=False)),
                ('PolicyMainId', models.ForeignKey(db_column='PolicyMainId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_products', to='core.policy_main')),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_products', to='core.ref_product')),
            ],
            options={
                'verbose_name': 'Policy Product',
                'verbose_name_plural': 'Policy Products',
                'db_table': 'ins_policy_main_product',
            },
        ),
        migrations.CreateModel(
            name='Policy_Main_Product_Item',
            fields=[
                ('PolicyMainProductItemId', models.AutoField(primary_key=True, serialize=False)),
                ('BeginDate', models.DateTimeField(blank=True, null=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('Valuation', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('CommPercent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('CommAmount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('ItemId', models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_product_items', to='core.ref_item')),
                ('PolicyMainProductId', models.ForeignKey(db_column='PolicyMainProductId', on_delete=django.db.models.deletion.PROTECT, related_name='product_items', to='core.policy_main_product')),
            ],
            options={
                'verbose_name': 'Policy Product Item',
                'verbose_name_plural': 'Policy Product Items',
                'db_table': 'ins_policy_main_product_item',
            },
        ),
        migrations.CreateModel(
            name='Policy_Main_Product_Item_Risk',
            fields=[
                ('PolicyMainProductItemRiskId', models.AutoField(primary_key=True, serialize=False)),
                ('RiskPercent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('PolicyMainProductItemId', models.ForeignKey(db_column='PolicyMainProductItemId', on_delete=django.db.models.deletion.PROTECT, related_name='item_risks', to='core.policy_main_product_item')),
                ('RiskId', models.ForeignKey(db_column='RiskId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_product_item_risks', to='core.ref_risk')),
            ],
            options={
                'verbose_name': 'Policy Product Item Risk',
                'verbose_name_plural': 'Policy Product Item Risks',
                'db_table': 'ins_policy_main_product_item_risk',
            },
        ),
        migrations.CreateModel(
            name='Policy_Main_Product_Item_Question',
            fields=[
                ('PolicyMainProductItemQuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(blank=True, max_length=300, null=True)),
                ('ItemQuestionId', models.ForeignKey(db_column='ItemQuestionId', on_delete=django.db.models.deletion.PROTECT, related_name='policy_product_item_questions', to='core.ref_item_question')),
                ('PolicyMainProductItemId', models.ForeignKey(db_column='PolicyMainProductItemId', on_delete=django.db.models.deletion.PROTECT, related_name='item_questions', to='core.policy_main_product_item')),
            ],
            options={
                'verbose_name': 'Policy Product Item Question',
                'verbose_name_plural': 'Policy Product Item Questions',
                'db_table': 'ins_policy_main_product_item_question',
            },
        ),
    ]
