# Generated by Django 4.2.23 on 2025-12-28 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_policy_main_product_policy_main_product_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_User_Branch',
            fields=[
                ('UserBranchId', models.AutoField(primary_key=True, serialize=False)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('BranchId', models.ForeignKey(db_column='BranchId', on_delete=django.db.models.deletion.PROTECT, related_name='user_branches', to='core.ref_branch')),
                ('ChannelId', models.ForeignKey(db_column='ChannelId', on_delete=django.db.models.deletion.PROTECT, related_name='user_branches', to='core.ref_channel')),
                ('UserId', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.PROTECT, related_name='user_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Branch',
                'verbose_name_plural': 'User Branches',
                'db_table': 'ins_ref_user_branch',
            },
        ),
    ]
