# Generated by Django 4.2.23 on 2025-12-28 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_ref_user_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ref_User_Branch',
            new_name='Ref_Branch_User',
        ),
        migrations.AlterModelTable(
            name='Ref_Branch_User',
            table='ins_ref_branch_user',
        ),
    ]
