# Generated by Django 4.2.23 on 2025-12-28 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_rename_user_branch_to_branch_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ref_branch_user',
            options={'verbose_name': 'Branch User', 'verbose_name_plural': 'Branch Users'},
        ),
        migrations.AlterField(
            model_name='policy_main',
            name='ApprovedBy',
            field=models.ForeignKey(blank=True, db_column='ApprovedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ref_branch_user',
            name='BranchId',
            field=models.ForeignKey(db_column='BranchId', on_delete=django.db.models.deletion.PROTECT, related_name='branch_users', to='core.ref_branch'),
        ),
        migrations.AlterField(
            model_name='ref_branch_user',
            name='ChannelId',
            field=models.ForeignKey(db_column='ChannelId', on_delete=django.db.models.deletion.PROTECT, related_name='branch_users', to='core.ref_channel'),
        ),
        migrations.AlterField(
            model_name='ref_branch_user',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.PROTECT, related_name='branch_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
