# Generated by Django 4.2.23 on 2025-12-28 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_make_approvedby_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Template_Design',
            fields=[
                ('DesignId', models.AutoField(primary_key=True, serialize=False)),
                ('TableNameEng', models.CharField(max_length=60)),
                ('TableNameMon', models.CharField(max_length=60)),
                ('FieldNameEng', models.CharField(max_length=60)),
                ('FieldNameMon', models.CharField(max_length=60)),
                ('IsStatic', models.BooleanField(default=False)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedDate', models.DateField(auto_now_add=True, null=True)),
                ('CreatedBy', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_template_designs', to=settings.AUTH_USER_MODEL)),
                ('PolicyTemplateId', models.ForeignKey(db_column='PolicyTemplateId', on_delete=django.db.models.deletion.PROTECT, related_name='template_designs', to='core.ref_policy_template')),
            ],
            options={
                'verbose_name': 'Template Design',
                'verbose_name_plural': 'Template Designs',
                'db_table': 'ins_ref_template_design',
            },
        ),
    ]
