# Generated by Django 4.2.23 on 2025-12-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ref_template_design'),
    ]

    operations = [
        # Step 1: Rename the model (this updates Django's state)
        migrations.RenameModel(
            old_name='Ref_Policy_Template_Transaction',
            new_name='Ref_Template_Account',
        ),
        # Step 2: Rename the field in Django's state
        migrations.RenameField(
            model_name='Ref_Template_Account',
            old_name='PolicyTemplateTransactionId',
            new_name='TemplateAccountId',
        ),
        # Step 3: Update the model's Meta options (table name and verbose names)
        migrations.AlterModelTable(
            name='Ref_Template_Account',
            table='ins_ref_template_account',
        ),
        migrations.AlterModelOptions(
            name='Ref_Template_Account',
            options={'verbose_name': 'Template Account', 'verbose_name_plural': 'Template Accounts'},
        ),
    ]
