# Generated by Django 4.2.23 on 2025-12-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_template_transaction_to_template_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy_main',
            name='CurrencyAmount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='ref_template_account',
            name='AccountId',
            field=models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.PROTECT, related_name='template_accounts', to='core.ref_account'),
        ),
        migrations.AlterField(
            model_name='ref_template_account',
            name='CashFlowId',
            field=models.ForeignKey(blank=True, db_column='CashFlowId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_accounts', to='core.ref_cashflow'),
        ),
        migrations.AlterField(
            model_name='ref_template_account',
            name='PolicyTemplateId',
            field=models.ForeignKey(db_column='PolicyTemplateId', on_delete=django.db.models.deletion.PROTECT, related_name='template_accounts', to='core.ref_policy_template'),
        ),
    ]
