# Generated by Django 4.2.23 on 2025-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_currency_amount_to_policy_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_risk',
            name='IsCoreRisk',
            field=models.BooleanField(default=True),
        ),
    ]
