# Generated by Django 4.2.23 on 2026-01-03 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_add_is_core_risk_to_ref_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy_main',
            name='AgentId',
            field=models.ForeignKey(db_column='AgentId', on_delete=django.db.models.deletion.PROTECT, related_name='agent_policies', to=settings.AUTH_USER_MODEL),
        ),
    ]
