# Generated by Django 4.2.23 on 2026-01-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_policy_main_agentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref_risk',
            name='ParentId',
        ),
    ]
