# Generated by Django 4.2.23 on 2026-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_parentid_from_ref_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy_main_product_item',
            name='BeginDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy_main_product_item',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
