# Generated by Django 5.2.4 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_policy_main_product_item_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref_account_type',
            name='AccountTypeName',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]

