# Generated by Django 5.2.4 on 2025-01-XX XX:XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_ref_account_type_accounttypename'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref_product_group',
            name='CreditAccountId',
            field=models.ForeignKey(
                blank=True,
                db_column='CreditAccountId',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='product_groups_credit',
                to='core.ref_account'
            ),
        ),
        migrations.AddField(
            model_name='ref_product_group',
            name='DebitAccountId',
            field=models.ForeignKey(
                blank=True,
                db_column='DebitAccountId',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='product_groups_debit',
                to='core.ref_account'
            ),
        ),
    ]

